# Generated by Django 2.0.9 on 2018-11-08 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('status', models.IntegerField()),
                ('reason', models.TextField()),
                ('charset', models.CharField(blank=True, max_length=100)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy.API')),
            ],
        ),
    ]
