# Generated by Django 2.1 on 2018-11-08 00:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_apicalllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicalllog',
            name='request_body',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='apicalllog',
            name='request_headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
