# Generated by Django 2.1 on 2018-11-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0004_auto_20181108_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicalllog',
            name='request_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='apicalllog',
            name='request_body',
            field=models.TextField(blank=True),
        ),
    ]
