# Generated by Django 2.1 on 2018-11-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0005_auto_20181109_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicalllog',
            name='request_body_binary',
            field=models.BinaryField(blank=True),
        ),
    ]
