# Generated by Django 2.1 on 2018-11-09 00:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CallbackCallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('request_path', models.CharField(blank=True, max_length=1000)),
                ('request_body', models.TextField(blank=True)),
                ('request_headers', django.contrib.postgres.fields.jsonb.JSONField()),
                ('content', models.TextField()),
                ('status', models.IntegerField()),
                ('reason', models.TextField()),
                ('charset', models.CharField(blank=True, max_length=100)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callbacks.Callback')),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='callback',
            name='methods',
            field=models.ManyToManyField(to='callbacks.Method'),
        ),
    ]
