# Generated by Django 2.1 on 2018-11-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0002_auto_20181109_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackcalllog',
            name='request_body_binary',
            field=models.BinaryField(blank=True),
        ),
    ]
